function MVPA_evidence_aggregate(sublist, type)

% created 6.28.17
% sublist - list of subjects to run - this will be the first 4 subjects
% until collection of all data.  then also we can organize as a sublist. 
% type - type of analysis - your choices are
% all - general remember/forget with valence
% SM - subsequent memory
% bar graphs - bar graphs



    for i = 1:length(subjnums)
remember_highconf_OLD = vertcat(results.remember.highconf.mean.OLD.face, ...
    results.remember.highconf.mean.OLD.scene,results.remember.highconf.mean.OLD.object, ...
    results.remember.highconf.mean.OLD.word, results.remember.highconf.mean.OLD.rest);


forget_highconf_OLD = vertcat(results.forget.highconf.mean.OLD.face, ...
    results.forget.highconf.mean.OLD.scene,results.forget.highconf.mean.OLD.object, ...
    results.forget.highconf.mean.OLD.word, results.forget.highconf.mean.OLD.rest);

remember_highconf_NEW = vertcat(results.remember.highconf.mean.NEW.face, ...
    results.remember.highconf.mean.NEW.scene,results.remember.highconf.mean.NEW.object, ...
    results.remember.highconf.mean.NEW.word, results.remember.highconf.mean.NEW.rest);

forget_highconf_NEW = vertcat(results.forget.highconf.mean.NEW.face, ...
    results.forget.highconf.mean.NEW.scene,results.forget.highconf.mean.NEW.object, ...
    results.forget.highconf.mean.NEW.word, results.forget.highconf.mean.NEW.rest);

remember_merged_OLD = vertcat(results.remember.merged.mean.OLD.face, ...
    results.remember.merged.mean.OLD.scene,results.remember.merged.mean.OLD.object, ...
    results.remember.merged.mean.OLD.word, results.remember.merged.mean.OLD.rest);

forget_merged_OLD = vertcat(results.forget.merged.mean.OLD.face, ...
    results.forget.merged.mean.OLD.scene,results.forget.merged.mean.OLD.object, ...
    results.forget.merged.mean.OLD.word, results.forget.merged.mean.OLD.rest);

remember_merged_NEW = vertcat(results.remember.merged.mean.NEW.face, ...
    results.remember.merged.mean.NEW.scene,results.remember.merged.mean.NEW.object, ...
    results.remember.merged.mean.NEW.word, results.remember.merged.mean.NEW.rest);

forget_merged_NEW = vertcat(results.forget.merged.mean.NEW.face, ...
    results.forget.merged.mean.NEW.scene,results.forget.merged.mean.NEW.object, ...
    results.forget.merged.mean.NEW.word, results.forget.merged.mean.NEW.rest);

%for 104
remember_highconf_OLD = vertcat(results.remember.highconf.mean.OLD.face, ...
    results.remember.highconf.mean.OLD.scene,results.remember.highconf.mean.OLD.object, ...
    results.remember.highconf.mean.OLD.word, results.remember.highconf.mean.OLD.rest);

forget_highconf_OLD = vertcat(results.forget.highconf.mean.OLD.face, ...
    results.forget.highconf.mean.OLD.scene,results.forget.highconf.mean.OLD.object, ...
    results.forget.highconf.mean.OLD.word, results.forget.highconf.mean.OLD.rest);

remember_highconf_NEW = vertcat(results.remember.highconf.acts.NEW.face, ...
    results.remember.highconf.acts.NEW.scene,results.remember.highconf.acts.NEW.object, ...
    results.remember.highconf.acts.NEW.word, results.remember.highconf.acts.NEW.rest);

forget_highconf_NEW = vertcat(results.forget.highconf.mean.NEW.face, ...
    results.forget.highconf.mean.NEW.scene,results.forget.highconf.mean.NEW.object, ...
    results.forget.highconf.mean.NEW.word, results.forget.highconf.mean.NEW.rest);

remember_merged_OLD = vertcat(results.remember.merged.mean.OLD.face, ...
    results.remember.merged.mean.OLD.scene,results.remember.merged.mean.OLD.object, ...
    results.remember.merged.mean.OLD.word, results.remember.merged.mean.OLD.rest);

forget_merged_OLD = vertcat(results.forget.merged.mean.OLD.face, ...
    results.forget.merged.mean.OLD.scene,results.forget.merged.mean.OLD.object, ...
    results.forget.merged.mean.OLD.word, results.forget.merged.mean.OLD.rest);

remember_merged_NEW = vertcat(results.remember.merged.acts.NEW.face, ...
    results.remember.merged.acts.NEW.scene,results.remember.merged.acts.NEW.object, ...
    results.remember.merged.acts.NEW.word, results.remember.merged.acts.NEW.rest);

forget_merged_NEW = vertcat(results.forget.merged.mean.NEW.face, ...
    results.forget.merged.mean.NEW.scene,results.forget.merged.mean.NEW.object, ...
    results.forget.merged.mean.NEW.word, results.forget.merged.mean.NEW.rest);



%%%%% BAR STUFFS %%%%%

remember_bar_precue = vertcat(results.remember.all.bar.precue.face.nanmean, results.remember.all.bar.precue.scene.nanmean, ...
    results.remember.all.bar.precue.object.nanmean, results.remember.all.bar.precue.word.nanmean, results.remember.all.bar.precue.rest.nanmean);

remember_bar_postcue = vertcat(results.remember.all.bar.postcue.face.nanmean, results.remember.all.bar.postcue.scene.nanmean, ...
    results.remember.all.bar.postcue.object.nanmean, results.remember.all.bar.postcue.word.nanmean, results.remember.all.bar.postcue.rest.nanmean);

forget_bar_precue = vertcat(results.forget.all.bar.precue.face.nanmean, results.forget.all.bar.precue.scene.nanmean, ...
    results.forget.all.bar.precue.object.nanmean, results.forget.all.bar.precue.word.nanmean, results.forget.all.bar.precue.rest.nanmean);

forget_bar_postcue = vertcat(results.forget.all.bar.postcue.face.nanmean, results.forget.all.bar.postcue.scene.nanmean, ...
    results.forget.all.bar.postcue.object.nanmean, results.forget.all.bar.postcue.word.nanmean, results.forget.all.bar.postcue.rest.nanmean);
%%%% scene and word normalised by face %%%%%

remember_bar_precue_facenorm = vertcat(results.remember.all.bar.precue.scene_facenorm.nanmean,  results.remember.all.bar.precue.word_facenorm.nanmean); 
remember_bar_postcue_facenorm = vertcat(results.remember.all.bar.postcue.scene_facenorm.nanmean,  results.remember.all.bar.postcue.word_facenorm.nanmean);

forget_bar_precue_facenorm = vertcat(results.forget.all.bar.precue.scene_facenorm.nanmean,  results.forget.all.bar.precue.word_facenorm.nanmean); 
forget_bar_postcue_facenorm = vertcat(results.forget.all.bar.postcue.scene_facenorm.nanmean,  results.forget.all.bar.postcue.word_facenorm.nanmean);

remember_bar_postminuspre_nofacenorm = vertcat(results.remember.all.bar.postminuspre.nofacenorm.scene.nanmean, results.remember.all.bar.postminuspre.nofacenorm.word.nanmean);
forget_bar_postminuspre_nofacenorm = vertcat(results.forget.all.bar.postminuspre.nofacenorm.scene.nanmean, results.forget.all.bar.postminuspre.nofacenorm.word.nanmean);

remember_bar_postminuspre_facenorm = vertcat(results.remember.all.bar.postminuspre.facenorm.scene.nanmean, results.remember.all.bar.postminuspre.facenorm.word.nanmean);
forget_bar_postminuspre_facenorm = vertcat(results.forget.all.bar.postminuspre.facenorm.scene.nanmean, results.forget.all.bar.postminuspre.facenorm.word.nanmean);


forget_merged_bar_OLD_precue = vertcat(results.forget.merged.bar.OLD.precue.face.nanmean,...
    results.forget.merged.bar.OLD.precue.scene.nanmean,results.forget.merged.bar.OLD.precue.object.nanmean,...
    results.forget.merged.bar.OLD.precue.word.nanmean,results.forget.merged.bar.OLD.precue.rest.nanmean);

    
forget_merged_bar_OLD_postcue = vertcat(results.remember.merged.bar.OLD.postcue.face.nanmean,...
    results.remember.merged.bar.OLD.postcue.scene.nanmean,results.remember.merged.bar.OLD.postcue.object.nanmean,...
    results.remember.merged.bar.OLD.postcue.word.nanmean,results.remember.merged.bar.OLD.postcue.rest.nanmean);

remember_merged_bar_NEW_precue = vertcat(results.remember.merged.bar.NEW.precue.face.nanmean,...
    results.remember.merged.bar.NEW.precue.scene.nanmean,results.remember.merged.bar.NEW.precue.object.nanmean,...
    results.remember.merged.bar.NEW.precue.word.nanmean,results.remember.merged.bar.NEW.precue.rest.nanmean);

remember_merged_bar_NEW_postcue = vertcat(results.remember.merged.bar.NEW.postcue.face.nanmean,...
    results.remember.merged.bar.NEW.postcue.scene.nanmean,results.remember.merged.bar.NEW.postcue.object.nanmean,...
    results.remember.merged.bar.NEW.postcue.word.nanmean,results.remember.merged.bar.NEW.postcue.rest.nanmean);

forget_merged_bar_OLD_precue = vertcat(results.forget.merged.bar.OLD.precue.face.nanmean,...
    results.forget.merged.bar.OLD.precue.scene.nanmean,results.forget.merged.bar.OLD.precue.object.nanmean,...
    results.forget.merged.bar.OLD.precue.word.nanmean,results.forget.merged.bar.OLD.precue.rest.nanmean);

    
forget_merged_bar_OLD_postcue = vertcat(results.forget.merged.bar.OLD.postcue.face.nanmean,...
    results.forget.merged.bar.OLD.postcue.scene.nanmean,results.forget.merged.bar.OLD.postcue.object.nanmean,...
    results.forget.merged.bar.OLD.postcue.word.nanmean,results.forget.merged.bar.OLD.postcue.rest.nanmean);

forget_merged_bar_NEW_precue = vertcat(results.forget.merged.bar.NEW.precue.face.nanmean,...
    results.forget.merged.bar.NEW.precue.scene.nanmean,results.forget.merged.bar.NEW.precue.object.nanmean,...
    results.forget.merged.bar.NEW.precue.word.nanmean,results.forget.merged.bar.NEW.precue.rest.nanmean);

forget_merged_bar_NEW_postcue = vertcat(results.forget.merged.bar.NEW.postcue.face.nanmean,...
    results.forget.merged.bar.NEW.postcue.scene.nanmean,results.forget.merged.bar.NEW.postcue.object.nanmean,...
    results.forget.merged.bar.NEW.postcue.word.nanmean,results.forget.merged.bar.NEW.postcue.rest.nanmean);


remember_highconf_bar_OLD_precue = vertcat(results.remember.highconf.bar.OLD.precue.face.nanmean,...
    results.remember.highconf.bar.OLD.precue.scene.nanmean,results.remember.highconf.bar.OLD.precue.object.nanmean,...
    results.remember.highconf.bar.OLD.precue.word.nanmean,results.remember.highconf.bar.OLD.precue.rest.nanmean);

    
remember_highconf_bar_OLD_postcue = vertcat(results.remember.highconf.bar.OLD.postcue.face.nanmean,...
    results.remember.highconf.bar.OLD.postcue.scene.nanmean,results.remember.highconf.bar.OLD.postcue.object.nanmean,...
    results.remember.highconf.bar.OLD.postcue.word.nanmean,results.remember.highconf.bar.OLD.postcue.rest.nanmean);

remember_highconf_bar_NEW_precue = vertcat(results.remember.highconf.bar.NEW.precue.face.nanmean,...
    results.remember.highconf.bar.NEW.precue.scene.nanmean,results.remember.highconf.bar.NEW.precue.object.nanmean,...
    results.remember.highconf.bar.NEW.precue.word.nanmean,results.remember.highconf.bar.NEW.precue.rest.nanmean);

remember_highconf_bar_NEW_postcue = vertcat(results.remember.highconf.bar.NEW.postcue.face.nanmean,...
    results.remember.highconf.bar.NEW.postcue.scene.nanmean,results.remember.highconf.bar.NEW.postcue.object.nanmean,...
    results.remember.highconf.bar.NEW.postcue.word.nanmean,results.remember.highconf.bar.NEW.postcue.rest.nanmean);

forget_highconf_bar_OLD_precue = vertcat(results.forget.highconf.bar.OLD.precue.face.nanmean,...
    results.forget.highconf.bar.OLD.precue.scene.nanmean,results.forget.highconf.bar.OLD.precue.object.nanmean,...
    results.forget.highconf.bar.OLD.precue.word.nanmean,results.forget.highconf.bar.OLD.precue.rest.nanmean);

    
forget_highconf_bar_OLD_postcue = vertcat(results.forget.highconf.bar.OLD.postcue.face.nanmean,...
    results.forget.highconf.bar.OLD.postcue.scene.nanmean,results.forget.highconf.bar.OLD.postcue.object.nanmean,...
    results.forget.highconf.bar.OLD.postcue.word.nanmean,results.forget.highconf.bar.OLD.postcue.rest.nanmean);

forget_highconf_bar_NEW_precue = vertcat(results.forget.highconf.bar.NEW.precue.face.nanmean,...
    results.forget.highconf.bar.NEW.precue.scene.nanmean,results.forget.highconf.bar.NEW.precue.object.nanmean,...
    results.forget.highconf.bar.NEW.precue.word.nanmean,results.forget.highconf.bar.NEW.precue.rest.nanmean);

forget_highconf_bar_NEW_postcue = vertcat(results.forget.highconf.bar.NEW.postcue.face.nanmean,...
    results.forget.highconf.bar.NEW.postcue.scene.nanmean,results.forget.highconf.bar.NEW.postcue.object.nanmean,...
    results.forget.highconf.bar.NEW.postcue.word.nanmean,results.forget.highconf.bar.NEW.postcue.rest.nanmean);


remember_neu_bar_precue= vertcat(results.remember.neu.bar.precue.face.nanmean,...
    results.remember.neu.bar.precue.scene.nanmean,results.remember.neu.bar.precue.object.nanmean,...
    results.remember.neu.bar.precue.word.nanmean,results.remember.neu.bar.precue.rest.nanmean);
remember_neu_bar_postcue= vertcat(results.remember.neu.bar.postcue.face.nanmean,...
    results.remember.neu.bar.postcue.scene.nanmean,results.remember.neu.bar.postcue.object.nanmean,...
    results.remember.neu.bar.postcue.word.nanmean,results.remember.neu.bar.postcue.rest.nanmean);

forget_neu_bar_precue= vertcat(results.forget.neu.bar.precue.face.nanmean,...
    results.forget.neu.bar.precue.scene.nanmean,results.forget.neu.bar.precue.object.nanmean,...
    results.forget.neu.bar.precue.word.nanmean,results.forget.neu.bar.precue.rest.nanmean);
forget_neu_bar_postcue= vertcat(results.forget.neu.bar.postcue.face.nanmean,...
    results.forget.neu.bar.postcue.scene.nanmean,results.forget.neu.bar.postcue.object.nanmean,...
    results.forget.neu.bar.postcue.word.nanmean,results.forget.neu.bar.postcue.rest.nanmean);

remember_neg_bar_precue= vertcat(results.remember.neg.bar.precue.face.nanmean,...
    results.remember.neg.bar.precue.scene.nanmean,results.remember.neg.bar.precue.object.nanmean,...
    results.remember.neg.bar.precue.word.nanmean,results.remember.neg.bar.precue.rest.nanmean);
remember_neg_bar_postcue= vertcat(results.remember.neg.bar.postcue.face.nanmean,...
    results.remember.neg.bar.postcue.scene.nanmean,results.remember.neg.bar.postcue.object.nanmean,...
    results.remember.neg.bar.postcue.word.nanmean,results.remember.neg.bar.postcue.rest.nanmean);

forget_neg_bar_precue= vertcat(results.forget.neg.bar.precue.face.nanmean,...
    results.forget.neg.bar.precue.scene.nanmean,results.forget.neg.bar.precue.object.nanmean,...
    results.forget.neg.bar.precue.word.nanmean,results.forget.neg.bar.precue.rest.nanmean);
forget_neg_bar_postcue= vertcat(results.forget.neg.bar.postcue.face.nanmean,...
    results.forget.neg.bar.postcue.scene.nanmean,results.forget.neg.bar.postcue.object.nanmean,...
    results.forget.neg.bar.postcue.word.nanmean,results.forget.neg.bar.postcue.rest.nanmean);






